Considering alternative parameter names for the Helmert pperator
busstoptaktik/geodesy pull request #91
Opened 2023-12-31 19:21 UTC by nrhill1

Considering alternative parameter names for the Helmert transformation -- this optionally allows for translation, rotation and trends to be provided as triplets rather than requiring each direction be denoted.  #45

2024-01-01 17:06 UTC, busstoptaktik requested changes
Thanks for working on this - it is a great improvement, although I have a handful of comments below.

Currently CI fails, due to `cargo clippy`. So remember to run cargo clippy, cargo fmt and make sure all tests pass. If you have the `just` utility installed (cargo install just) you can do this by saying `just check`.

2024-01-01 21:40 UTC, nrhill1 commented on src/inner_op/helmert.rs
> +    let DS = (params.real("ds")? + params.real("scale_trend")?) * 1e-6;
I've made these variables conditional statements similar to the others above.

2024-01-01 21:40 UTC, nrhill1 commented
Hi Thomas,

Thanks for the suggestions -- I've went ahead and made the improvements.

2024-01-02 08:29 UTC, busstoptaktik approved these changes
Thanks for completing this! I will update the documentation to reflect these improvements later today.

Your work has revealed how bad an idea it was, on my part, to represent the default for a `series` as a string (`"0,0,0"` in this case), so I will probably change the API before too long, and hence also update the relevant places in your work.

But once again: Thank you for providing this work - it is much appreciated! Feel free to continue the collaboration if there is anyting you feel the Geodesy crate misses!

2024-01-02 08:29 UTC, busstoptaktik commented on src/context/mod.rs
> -pub use minimal::Minimal;
The update to version 1.75 appears to have made Clippy a bit smarter wrt. detecting unused imports, making the changes in mod.rs necessary. I first updated from 1.74 this morning, so I hadn't noticed before

2024-01-02 08:35 UTC, merged